#!/bin/bash
#
# MIT
#
# Bash script to add funcitonality to todo.txt cli by Gina Trapani. Most
# Important Tasks (MIT) are intended to be specific todo items associated
# with a specific day. They differ from events in that they do not necessarily
# have a specified time. As a best practice only 3 MITs should be scheduled
# per day. This script is intended to parse the todo.txt file and generate a
# schedule of MITs by day of the week if no arguments are given, or add new
# MITs to the list.
#
# MITs are stored in the following format:
#   {YYYY.MM.DD} mit task information
#
# Author(s): Cody Buell
#
# Licensing: GPL, http://www.gnu.org/copyleft/gpl.html
#
# Revisions: 2012.06.27 Framework roughed out.
#            2012.06.28 Initial version completed.
#            2012.06.29 Moved away from using DOY to prevent problems in
#                       spanning years.
#            2012.07.01 Added ability to move MITs.
#            2012.07.02 Made greps a bit more robust.
#            2012.07.13 Added ability to invert context listings.
#            2012.09.22 Modified greps and seds to handle MITs with priorities.
#            2012.10.29 Merged corrections from 00Davo regarding #2.
#
# Requisite: todo.sh by Gina Trapanni
#
# Resources: https://github.com/ginatrapani/todo.txt-cli/wiki
#
# Task List: Add extra check on mit mv to see that it is an MIT being moved.
#            Add ability to add a time {YYYY.MM.DD HH:MMam/pm}
#             t mit today@10pm go to work @nasa

###################
# Usage Functions #
###################

usage() {
  cat <<-ENDOFUSAGE

	  Most Important Tasks (MIT):
	    Displays from or adds Most Important Tasks (MIT) to todo.txt file.

	    $(basename $0) [-hv] [date|day task] [not @context|@context] [mv ID DATE|DAY]

	    -h, --help      Displays help message.
	    -v, --version   Displays version information.

	    mit DATE|DAY task
	      DATE must be in the format of YYYY.MM.DD.
	      DAY can be full or short day names, today or tomorrow.

	    mit not @context|@context
	      Displays all MIT's not in or in specified context.

	    mit mv ID DATE|DAY
	      Move the MIT identified by ID to a new day.
	      DATE must be in the format of YYYY.MM.DD.
	      DAY can be full or short day names, today or tomorrow.

	    mit wed upload code to github
	      Creates a new MIT for next Wednesday unless the current day
	      is Wednesday in which case it will be created for today.

	ENDOFUSAGE
  exit
}

error() {
  echo "error: $1"
  echo "usage: $(basename $0) [-hv] [date|day task] [not @context|@context] [mv ID DATE|DAY]"
}

####################
# Helper Funcitons #
####################

makeDOW() {
  # format YYYY.MM.DD to day of week (Monday)
  if [ $DVER = "BSD" ]; then
    eval $1=`date -j -f "%Y.%m.%d" $2 +%A`
  else
    local DAY=`echo $2 | sed 's/\./\//g'`
    eval $1=`date -d $DAY +%A`
  fi
}

makeDATE() {
  # format YYYY.MM.DD to Day, Month DD
  if [ $DVER = "BSD" ]; then
    eval $1=`date -j -f "%Y.%m.%d" $2 "+%A', '%B' '%d"`
  else
    local DAY=`echo $2 | sed 's/\./\//g'`
    eval $1=`date -d $DAY "+%A', '%B' '%d"`
  fi
}

parseDAY() {
  # create YYYY.MM.DD from upcoming day of week
  if [ $DVER = "BSD" ]; then
    MITDATE=`date -v +$1 +%Y.%m.%d`
  else
	  local dayid=$1
	  if [ $dayid = "1d" ]; then
		  dayid="1day"
	  fi
    MITDATE=`date -d +$dayid +%Y.%m.%d`
  fi
}

getMITS() {
  # print out mits matching specific date criteria
  for (( i=0; i < ${#MITS[@]}; i++ )); do
    MITDATE=`echo ${MITS[$i]} | awk '{print $1}' | sed 's/\.//g'`
    MITTASK=`echo ${MITS[$i]} | awk '{$1 = ""; print}'`
    if [ "$MITDATE" $1 "$2" ]; then
      echo " $MITTASK"
    fi
  done
}

#######################
# Establish Variables #
#######################

if date -v 1d > /dev/null 2>&1; then    # detect date version in use
  DVER="BSD"                            # set as bsd date
else                                    # if it isn't bsd then...
  DVER="GNU"                            # set as gnu date
fi

VERSION="1.1"                           # mit version number
ACTION=$1                               # set first argument to action

shift                                   # shift arguments

##########
# Run It #
##########

# USAGE AND HELP

[ "$ACTION" = "usage" ] || [ x"$1" = x"-h" ] || [ x"$1" = x"--help" ] && {
  usage
}

# VERSION INFORMATION

[ x"$1" = x"-v" ] || [ x"$1" = x"--version" ] && {
  echo "mit verion $VERSION"
  exit
}

# MOVE MITS

[ x"$1" = x"mv" ] && {
  # check that second argument is an id and a valid one
  if [[ $2 =~ ^[0-9]+$ ]]; then
    MITTASK=`awk -v ID=$2 'NR==ID {$1=""; sub(/^ /, ""); print "\x27"$0"\x27"}' $TODO_FILE`
    case $3 in
      today )
        MITDATE="`date +%Y.%m.%d`"
        sed -i '' "$2 s/{[0-9]\{4\}\.[0-9]\{2\}\.[0-9]\{2\}}/{$MITDATE}/" $TODO_FILE
        echo "TODO: MIT $MITTASK moved to today."
        exit
        ;;
      tomorrow )
        parseDAY 1d
        sed -i '' "$2 s/{[0-9]\{4\}\.[0-9]\{2\}\.[0-9]\{2\}}/{$MITDATE}/" $TODO_FILE
        echo "TODO: MIT $MITTASK moved to tomorrow."
        exit
        ;;
      monday|mon|tuesday|tue|wednesday|wed|thursday|thu|friday|fri|saturday|sat|sunday|sun )
        parseDAY $3
        makeDOW DOW $MITDATE
        sed -i '' "$2 s/{[0-9]\{4\}\.[0-9]\{2\}\.[0-9]\{2\}}/{$MITDATE}/" $TODO_FILE
        echo "TODO: MIT $MITTASK moved to $DOW."
        exit
        ;;
      [0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9] )
        makeDATE DATE $3
        sed -i '' "$2 s/{[0-9]\{4\}\.[0-9]\{2\}\.[0-9]\{2\}}/{$3}/" $TODO_FILE
        echo "TODO: MIT $MITTASK moved to $DATE."
        exit
        ;;
      * )
        error "invalid date"
        exit
        ;;
    esac
  fi

  error "invalid task id"
  exit
}

# DISPLAY MITS

[ -z $1 ] || [[ $1 =~ @.* ]] || [ "$1" = "not" ] && {

  # define array element separator as newlines
  OLDIFS=$IFS
  IFS=$'\n'

  # invert search if not is specified before context
  if [ "$1" = "not" ]; then
    shift
    FLAG="-v"
  else
    FLAG=""
  fi

  # pull out MITs from the todo file, clean and sort
  MITS=(`grep -n "^([A-Z]\{1\}) {[0-9]\{4\}\.[0-9]\{2\}\.[0-9]\{2\}\|^{[0-9]\{4\}\.[0-9]\{2\}\.[0-9]\{2\}" $TODO_FILE | grep $FLAG "$1" | sed -e 's/{//' -e 's/}//' -e 's/:/ /' -e 's/\(^[0-9].* \)\(([A-Z]) \)\([0-9]\{4\}\.[0-9]\{2\}\.[0-9]\{2\} \)\(.*\)/\1\3\2\4/' | awk '{s=$1;e=$NF;$1="";$NF=e" ("s")"}1' | sort`)

  # return array element separator to spaces
  IFS=$OLDIFS

  # make an array of ordered unique MIT dates
  DATES=(`grep "^([A-Z]\{1\}) {[0-9]\{4\}\.[0-9]\{2\}\.[0-9]\{2\}\|^{[0-9]\{4\}\.[0-9]\{2\}\.[0-9]\{2\}" $TODO_FILE | grep $FLAG "$1" | sed -e 's/{//' -e 's/}//' -e 's/([A-Z]\{1\})//' | awk '{print $1}' | sort | uniq`)
  TODAY=`date +%Y%m%d`

  # processing if there are no mits
  if [ "${#DATES[@]}" -eq "0" ]; then
    echo "No MITs found."
    exit
  fi

  # processing of past due mits
  PASTDUE="false"
  for day in ${DATES[@]}; do
    DAY=`echo $day | sed 's/\.//g'`
    if [ "$DAY" -lt "$TODAY" ]; then
      PASTDUE="true"
    fi
  done
  if [ "$PASTDUE" = "true" ]; then
    echo "Past Due:"
    getMITS -lt $TODAY
    echo ""
  fi

  # processing of all other mits
  for day in ${DATES[@]}; do

    DAY=`echo $day | sed 's/\.//g'`
    DAYSTO=$(( $DAY - $TODAY ))

    if [ "$DAY" -eq "$TODAY" ]; then
      echo "Today:"
      getMITS -eq $DAY
      echo ""

    elif [ "$DAYSTO" -gt "0" ] && [ "$DAYSTO" -lt "7" ]; then
      makeDOW DOW $day
      echo "$DOW:"
      getMITS -eq $DAY
      echo ""

    elif [ "$DAYSTO" -ge "7" ]; then
      makeDATE DATE $day
      echo "$DATE:"
      getMITS -eq $DAY
      echo ""
    fi

  done
  exit

}

# ADD NEW MITS

[ -n "$1" ] && {

  MITDATE=`echo $1 | tr [A-Z] [a-z]`
  shift
  MITTASK=$@
  TODAY=`date +%u`

  case $MITDATE in
    today )
      NEWMIT="{`date +%Y.%m.%d`} $MITTASK"
      ;;
    tomorrow )
      parseDAY 1d
      NEWMIT="{$MITDATE} $MITTASK"
      ;;
    monday|mon|tuesday|tue|wednesday|wed|thursday|thu|friday|fri|saturday|sat|sunday|sun )
      parseDAY $MITDATE
      NEWMIT="{$MITDATE} $MITTASK"
      ;;
    [0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9] )
      NEWMIT="{$MITDATE} $MITTASK"
      ;;
    * )
      error "invalid date"
      exit
      ;;
  esac

  $TODO_FULL_SH add $NEWMIT

  exit

}
